version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elasticsearch.example.org
